name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3  # Updated from v2 to v3

      - name: Set up Node.js
        uses: actions/setup-node@v3  # Updated from v2 to v3
        with:
          node-version: '16'  # Ensures Node.js 16 is used

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy
        run: npm run deploy
