name: SonarQube Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18' 

      - name: Install dependencies
        run: npm install

      - name: SonarQube Analysis
        run: npx sonar-scanner

      - name: Upload SonarQube results
        uses: sonarsource/sonarcloud-github-action@v2
        with:
          token: ${{ secrets.SONAR_TOKEN }}
